package application;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.intellijthemes.FlatDraculaIJTheme;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author knovengel
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    
    private static App instance;
    
    public App() {
        initComponents();
        instance = this;
        updatePanel(0);
    }
    
    public static void update(int code){
        instance.updatePanel(code);
    }
    
    public void updatePanel(int code){
        if(instance != null){
            leftPanel.removeAll();
            leftPanel.setLayout(new java.awt.BorderLayout());
            updateLeftPanel(code);
            leftPanel.revalidate();
            leftPanel.repaint();
        
            rightPanel.removeAll();
            rightPanel.setLayout(new java.awt.BorderLayout());
            updateRightPanel(code);
            rightPanel.revalidate();
            rightPanel.repaint();
        }
    }
    
    public void updateLeftPanel(int code){
        if(instance != null){
            switch(code){
                case 0:
                    leftPanel.add(new InitialMenu());
                    break;
                
                case 1:
                    leftPanel.add(new InitialMenu());
                    break;
                    
                case 2:
                    leftPanel.add(new InitialMenu());
                    break;
                
                case 3:
                    leftPanel.add(new NextMenu());
                    break;
                    
                case 4:
                    leftPanel.add(new NextMenu());
                    break;
                
                case 5:
                    leftPanel.add(new NextMenu());
                    break;
                    
                case 6:
                    leftPanel.add(new NextMenu());
                    break;
                
                case 7:
                    leftPanel.add(new NextMenu());
                    break;
                    
                case 8:
                    leftPanel.add(new NextMenu());
                    break;
                    
                case 9:
                    leftPanel.add(new NextMenu());
                    break;
            
            }
        }
    }
    
    public void updateRightPanel(int code){
        if(instance != null){
            switch(code){
                case 0:
                    rightPanel.add(new imagePanel());
                    break;
                
                case 1:
                    rightPanel.add(new LoginPage());
                    break;
                    
                case 2:
                    rightPanel.add(new RegisterPage());
                    break;
                
                case 3:
                    rightPanel.add(new imagePanel());
                    break;
                    
                case 4:
                    rightPanel.add(new WithdrawPage());
                    break;
                
                case 5:
                    rightPanel.add(new DepositPage());
                    break;
                    
                case 6:
                    rightPanel.add(new MyTransactionsPage());
                    break;
                
                case 7:
                    rightPanel.add(new ChangePinPage());
                    break;
                    
                case 8:
                    rightPanel.add(new MyInfoPage());
                    break;
                
                case 9:
                    rightPanel.add(new UpdateInfoPage());
                    break;
            
            }
        }
    }
    
    public static void run(){
        main(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank System V 0.0.69");
        setResizable(false);

        leftPanel.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        rightPanel.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDraculaIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
