package application;

import javax.swing.JOptionPane;

/**
 *
 * @author knovengel
 */
public class ChangePinPage extends javax.swing.JPanel {

    /**
     * Creates new form ChangePinPage
     */
    public ChangePinPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatePinButton = new javax.swing.JButton();
        confirmNewPinTitle = new javax.swing.JLabel();
        confirmNewPinTextField = new javax.swing.JPasswordField();
        changePinTitle = new javax.swing.JLabel();
        oldPinTitle = new javax.swing.JLabel();
        newPinTitle = new javax.swing.JLabel();
        newPinTextField = new javax.swing.JPasswordField();
        oldPinTextField = new javax.swing.JPasswordField();

        updatePinButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        updatePinButton.setText("Update Pin");
        updatePinButton.setToolTipText("Click to Update you'r Old Pin");
        updatePinButton.setBorderPainted(false);
        updatePinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatePinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePinButtonActionPerformed(evt);
            }
        });

        confirmNewPinTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        confirmNewPinTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmNewPinTitle.setText("Confirm New Pin");

        confirmNewPinTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        confirmNewPinTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmNewPinTextField.setToolTipText("Confirm you'r New Pin.");

        changePinTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        changePinTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changePinTitle.setText("Change Pin");

        oldPinTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        oldPinTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oldPinTitle.setText("Old Pin");

        newPinTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        newPinTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newPinTitle.setText("New Pin");

        newPinTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        newPinTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newPinTextField.setToolTipText("Enter you'r New Pin.");

        oldPinTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        oldPinTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oldPinTextField.setToolTipText("Enter you'r Old Pin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changePinTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(confirmNewPinTextField)
                                .addComponent(confirmNewPinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(newPinTextField)
                                .addComponent(oldPinTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newPinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(oldPinTextField)))
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updatePinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(changePinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(oldPinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(newPinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmNewPinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmNewPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(updatePinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatePinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePinButtonActionPerformed
        // TODO add your handling code here:
        int oldPin = Integer.parseInt(oldPinTextField.getText());
        int newPin = Integer.parseInt(newPinTextField.getText());
        int confirmNewPin = Integer.parseInt(confirmNewPinTextField.getText());

        if (newPin == confirmNewPin) {
            boolean success = Application.DB.changePin(Application.currentActiveAccount.getAccountNumber(), oldPin, newPin);
            if (success) {
                System.out.println("Pin Updated Successfully");
                App.update(3);
                JOptionPane.showMessageDialog(null, "Pin Updated Successfuly!", "Pin Update", JOptionPane.INFORMATION_MESSAGE);
    
            } else {
                System.out.println("Old pin is incorrect or account not found.");
                JOptionPane.showMessageDialog(null, "Old pin is Incorrect!", "Authentication Error", JOptionPane.ERROR_MESSAGE);
            }
        }else {
            System.out.println("New pin and confirm new pin are not the same");
                JOptionPane.showMessageDialog(null, "Old pin Does not Match with New Pin!", "Authentication Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updatePinButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changePinTitle;
    private javax.swing.JPasswordField confirmNewPinTextField;
    private javax.swing.JLabel confirmNewPinTitle;
    private javax.swing.JPasswordField newPinTextField;
    private javax.swing.JLabel newPinTitle;
    private javax.swing.JPasswordField oldPinTextField;
    private javax.swing.JLabel oldPinTitle;
    private javax.swing.JButton updatePinButton;
    // End of variables declaration//GEN-END:variables
}
