/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application;

import javax.swing.JOptionPane;

/**
 *
 * @author knovengel
 */
public class DepositPage extends javax.swing.JPanel {

    /**
     * Creates new form DepositPage
     */
    public DepositPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositButton = new javax.swing.JButton();
        depositTitle = new javax.swing.JLabel();
        amountTitle = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();

        depositButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.setToolTipText("Click to Deposit the Entered Amount");
        depositButton.setBorderPainted(false);
        depositButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        depositTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        depositTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositTitle.setText("Deposit");

        amountTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        amountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountTitle.setText("Amount");

        amountTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        amountTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountTextField.setToolTipText("Enter Amount to be Deposited.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(depositTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(amountTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(amountTextField))
                        .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(depositTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(amountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        double amount = Double.parseDouble(amountTextField.getText());
        if(Integer.parseInt(amountTextField.getText())>0){
            Application.currentActiveAccount.deposit(amount);
            String msg = "Account Deposited with "+amount;
            System.out.println(msg);
            App.update(3);
            JOptionPane.showMessageDialog(null, msg, "Deposit", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Amount cannot be less than or Equal to 0", "Deposit", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_depositButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTextField;
    private javax.swing.JLabel amountTitle;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel depositTitle;
    // End of variables declaration//GEN-END:variables
}
