/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application;

import javax.swing.JOptionPane;

/**
 *
 * @author knovengel
 */
public class LoginPage extends javax.swing.JPanel {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTitle = new javax.swing.JLabel();
        accountNumberTitle = new javax.swing.JLabel();
        accountNumberTextField = new javax.swing.JTextField();
        pinTitle = new javax.swing.JLabel();
        pinTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        loginTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("Login");

        accountNumberTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        accountNumberTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountNumberTitle.setText("Account Number");

        accountNumberTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        accountNumberTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        accountNumberTextField.setToolTipText("Enter you'r Account Number.");

        pinTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        pinTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pinTitle.setText("Pin");

        pinTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        pinTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinTextField.setToolTipText("Enter you'r Pin.");

        loginButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        loginButton.setText("Login");
        loginButton.setToolTipText("Click to Log in with the given Credentials");
        loginButton.setBorderPainted(false);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountNumberTextField)
                            .addComponent(pinTextField)
                            .addComponent(accountNumberTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(pinTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(accountNumberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        int accountNumber = Integer.parseInt(accountNumberTextField.getText());
        int pin = Integer.parseInt(pinTextField.getText());
        if(Application.DB.authenticateAccount(accountNumber, pin)){
            System.out.println("Logged in");
            Application.currentActiveAccount = Application.DB.findAccount(accountNumber);
            App.update(3);
            JOptionPane.showMessageDialog(null, "You are Successfuly Signed In", "Sign in", JOptionPane.INFORMATION_MESSAGE);
        }else{
            System.out.println("Incorrect credentials");
            JOptionPane.showMessageDialog(null, "Incorrect Credentials!", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumberTextField;
    private javax.swing.JLabel accountNumberTitle;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JPasswordField pinTextField;
    private javax.swing.JLabel pinTitle;
    // End of variables declaration//GEN-END:variables
}
