/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application;

/**
 *
 * @author knovengel
 */
public class MyTransactionsPage extends javax.swing.JPanel {

    /**
     * Creates new form MyTransactionsPage
     */
    public MyTransactionsPage() {
        initComponents();
        for(int i=0; i<Application.currentActiveAccount.accountTransactions.size(); i++){
            textArea.append(Application.currentActiveAccount.accountTransactions.get(i)+"\n");
        }
        textArea.append("----------------------------------------------------\nAccount Balance \t "+Application.currentActiveAccount.getAccountBalance());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myTransactionsTitle = new javax.swing.JLabel();
        transactionsScroll = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        myTransactionsTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        myTransactionsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myTransactionsTitle.setText("My Transactions");

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        transactionsScroll.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myTransactionsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionsScroll)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(myTransactionsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transactionsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel myTransactionsTitle;
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane transactionsScroll;
    // End of variables declaration//GEN-END:variables
}
