/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application;

import javax.swing.JOptionPane;

/**
 *
 * @author knovengel
 */
public class NextMenu extends javax.swing.JPanel {

    /**
     * Creates new form NextMenu
     */
    public NextMenu() {
        initComponents();
        accountNumberLabel.setText(" < "+Application.currentActiveAccount.getAccountNumber()+" >");
        accountBalanceLabel.setText("$ "+Application.currentActiveAccount.getAccountBalance()+" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        myTransactionsButton = new javax.swing.JButton();
        changePinButton = new javax.swing.JButton();
        myInfoButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        accountNumberLabel = new javax.swing.JLabel();
        accountBalanceLabel = new javax.swing.JLabel();

        depositButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.setToolTipText("Deposit Money into the Account");
        depositButton.setBorderPainted(false);
        depositButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        withdrawButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        withdrawButton.setText("Withdraw");
        withdrawButton.setToolTipText("Withdraw Money from the Account");
        withdrawButton.setBorderPainted(false);
        withdrawButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        myTransactionsButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        myTransactionsButton.setText("My Transactions");
        myTransactionsButton.setToolTipText("Check You'r Transaction History");
        myTransactionsButton.setBorderPainted(false);
        myTransactionsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myTransactionsButtonActionPerformed(evt);
            }
        });

        changePinButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        changePinButton.setText("Change Pin");
        changePinButton.setToolTipText("Change You'r Account Pin");
        changePinButton.setBorderPainted(false);
        changePinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePinButtonActionPerformed(evt);
            }
        });

        myInfoButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        myInfoButton.setText("My Info");
        myInfoButton.setToolTipText("Check out You'r Info");
        myInfoButton.setBorderPainted(false);
        myInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myInfoButtonActionPerformed(evt);
            }
        });

        logOutButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.setToolTipText("Log out!");
        logOutButton.setBorderPainted(false);
        logOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        accountNumberLabel.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        accountNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        accountNumberLabel.setText("2024300169");

        accountBalanceLabel.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        accountBalanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accountBalanceLabel.setText("$ 269999");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changePinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myTransactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(accountNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accountBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myTransactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changePinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        // TODO add your handling code here:
        App.update(4);
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        App.update(5);
    }//GEN-LAST:event_depositButtonActionPerformed

    private void myTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myTransactionsButtonActionPerformed
        // TODO add your handling code here:
        App.update(6);
    }//GEN-LAST:event_myTransactionsButtonActionPerformed

    private void changePinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePinButtonActionPerformed
        // TODO add your handling code here:
        App.update(7);
    }//GEN-LAST:event_changePinButtonActionPerformed

    private void myInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myInfoButtonActionPerformed
        // TODO add your handling code here:
        App.update(8);
    }//GEN-LAST:event_myInfoButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Logged out");
        App.update(0);
    }//GEN-LAST:event_logOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBalanceLabel;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JButton changePinButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton myInfoButton;
    private javax.swing.JButton myTransactionsButton;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
