package application;

import javax.swing.JOptionPane;

/**
 *
 * @author knovengel
 */
public class RegisterPage extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regesterTitle = new javax.swing.JLabel();
        accountNumberTitle = new javax.swing.JLabel();
        accountNumberTextField = new javax.swing.JTextField();
        pinTitle = new javax.swing.JLabel();
        pinTextField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        confirmPinTitle = new javax.swing.JLabel();
        confirmPinTextField = new javax.swing.JPasswordField();

        regesterTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        regesterTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regesterTitle.setText("Sign Up");

        accountNumberTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        accountNumberTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountNumberTitle.setText("Account Number");

        accountNumberTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        accountNumberTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        accountNumberTextField.setToolTipText("Enter you'r Account Number.");

        pinTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        pinTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pinTitle.setText("Pin");

        pinTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        pinTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinTextField.setToolTipText("Enter you'r Pin.");

        registerButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        registerButton.setText("Sign Up");
        registerButton.setToolTipText("Register");
        registerButton.setBorderPainted(false);
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        confirmPinTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        confirmPinTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmPinTitle.setText("Confirm Pin");

        confirmPinTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        confirmPinTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPinTextField.setToolTipText("Enter you'r Pin.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regesterTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(confirmPinTextField)
                                .addComponent(confirmPinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(accountNumberTextField)
                                .addComponent(pinTextField)
                                .addComponent(accountNumberTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(regesterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(accountNumberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmPinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        int accountNumber = Integer.parseInt(accountNumberTextField.getText());
        int pin = Integer.parseInt(pinTextField.getText());
        int confirmPin = Integer.parseInt(confirmPinTextField.getText());
        if(pin == confirmPin){
            if(Application.DB.ifAccountExists(accountNumber)){
                System.out.println("Account Already Exists");
                JOptionPane.showMessageDialog(null, "Account already Exists!", "Error", JOptionPane.ERROR_MESSAGE);

            }else{
                Account acc = new Account(accountNumber, pin);
                System.out.println("Account added to Database");
                Application.DB.addAccount(acc);
                Application.currentActiveAccount = acc;
                App.update(3);
                JOptionPane.showMessageDialog(null, "Account Added to the Database Successfully", "Sign Up", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            System.out.println("Pin doesnt Match confirm pin");
            JOptionPane.showMessageDialog(null, "Pin doesnt Match confirm pin", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_registerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumberTextField;
    private javax.swing.JLabel accountNumberTitle;
    private javax.swing.JPasswordField confirmPinTextField;
    private javax.swing.JLabel confirmPinTitle;
    private javax.swing.JPasswordField pinTextField;
    private javax.swing.JLabel pinTitle;
    private javax.swing.JLabel regesterTitle;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
