/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application;

import javax.swing.JOptionPane;

/**
 *
 * @author knovengel
 */
public class UpdateInfoPage extends javax.swing.JPanel {

    /**
     * Creates new form UpdateInfoPage
     */
    public UpdateInfoPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateInfoTitle = new javax.swing.JLabel();
        newNameTitle = new javax.swing.JLabel();
        newNameTextField = new javax.swing.JTextField();
        newAgeTitle = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        newAgeTextField = new javax.swing.JTextField();

        updateInfoTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        updateInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateInfoTitle.setText("Update Info");

        newNameTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        newNameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newNameTitle.setText("New Name");

        newNameTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        newNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newNameTextField.setToolTipText("Enter you'r Name.");
        newNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNameTextFieldActionPerformed(evt);
            }
        });

        newAgeTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        newAgeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newAgeTitle.setText("New Age");

        updateButton.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        updateButton.setText("Update");
        updateButton.setToolTipText("Update You'r Information");
        updateButton.setBorderPainted(false);
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        newAgeTextField.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        newAgeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newAgeTextField.setToolTipText("Enter you'r Age.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateInfoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newNameTextField)
                            .addComponent(newNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(newAgeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newAgeTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(updateInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(newNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(newAgeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Info updated succesfully");
        String newName = newNameTextField.getText();
        int newAge = Integer.parseInt(newAgeTextField.getText());
        Application.currentActiveAccount.setName(newName);
        Application.currentActiveAccount.setAge(newAge);
        App.update(8);
        JOptionPane.showMessageDialog(null, "User Info Updated Successfully!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void newNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField newAgeTextField;
    private javax.swing.JLabel newAgeTitle;
    private javax.swing.JTextField newNameTextField;
    private javax.swing.JLabel newNameTitle;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel updateInfoTitle;
    // End of variables declaration//GEN-END:variables
}
